name: screen_security_kit
description: A Flutter plugin to prevent screenshots/recordings on Android, notify on iOS screenshots, and blur/whiteout app switcher previews.
version: 0.0.4
homepage: https://github.com/RakibDev25/flutter_screen_security_kit
repository: https://github.com/RakibDev25/flutter_screen_security_kit
issue_tracker: https://github.com/RakibDev25/flutter_screen_security_kit/issues
documentation: https://github.com/RakibDev25/flutter_screen_security_kit#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.screensecuritykit
        pluginClass: ScreenSecurityKitPlugin
      ios:
        pluginClass: ScreenSecurityKitPlugin
